# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      mono-pkg:
        update-types:
          - patch
          - minor
          - major
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    groups:
      ui-pkg:
        update-types:
          - patch
          - minor
          - major
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "monthly"
    groups:
      vm-pkg:
        update-types:
          - patch
          - minor
          - major
  - package-ecosystem: "npm"
    directory: "/utils"
    schedule:
      interval: "monthly"
    groups:
      utils-pkg:
        update-types:
          - patch
          - minor
          - major
