version: "3.8"

services:
  neurontainer:
    image: ${DESKTOP_PLUGIN_IMAGE}
    ports:
      - "3000:3000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # Mount Docker socket to allow backend to communicate with Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
      - neurontainer-data:/data
    extra_hosts:
      - host.docker.internal:host-gateway
      - docker.internal:host-gateway
volumes:
  neurontainer-data: